services:
  - type: web
    name: ladha-house-backend
    env: python
    repo: https://github.com/Craigmacharia/ladha-house
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ladha-house-1.onrender.com
    autoDeploy: true
