services:
  - type: web
    name: ladhahouse-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "ladhahouse-backend.onrender.com"


python manage.py migrate && python manage.py create_initial_admin && python manage.py collectstatic --noinput
